@startuml
set separator none
title Salesforce - Permission Set Groups - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Person(Sales, "Sales", $descr="", $tags="", $link="")
Person(Manager, "Manager", $descr="", $tags="", $link="")
Person(Canvasser, "Canvasser", $descr="", $tags="", $link="")
Person(Accounting, "Accounting", $descr="", $tags="", $link="")
Person(ProjectManager, "Project Manager", $descr="", $tags="", $link="")
Person(Dispatcher, "Dispatcher", $descr="", $tags="", $link="")

Container_Boundary("Salesforce.PermissionSetGroups_boundary", "Permission Set Groups", $tags="") {
  Component(Salesforce.PermissionSetGroups.Sales, "Sales", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.PermissionSetGroups.Manager, "Manager", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.PermissionSetGroups.Canvasser, "Canvasser", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.PermissionSetGroups.Dispatcher, "Dispatcher", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.PermissionSetGroups.Accounting, "Accounting", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.PermissionSetGroups.ProjectManager, "Project Manager", $techn="", $descr="", $tags="", $link="")
}

Rel(Sales, Salesforce.PermissionSetGroups.Sales, "Has", $techn="", $tags="", $link="")
Rel(Manager, Salesforce.PermissionSetGroups.Manager, "Has", $techn="", $tags="", $link="")
Rel(Canvasser, Salesforce.PermissionSetGroups.Canvasser, "Has", $techn="", $tags="", $link="")
Rel(Dispatcher, Salesforce.PermissionSetGroups.Dispatcher, "Has", $techn="", $tags="", $link="")
Rel(Accounting, Salesforce.PermissionSetGroups.Accounting, "Has", $techn="", $tags="", $link="")
Rel(ProjectManager, Salesforce.PermissionSetGroups.ProjectManager, "Has", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml