@startuml
set separator none
title Salesforce - Reports/Dashboards - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Container(Salesforce.SalesApp, "Sales App", $techn="", $descr="[Standard]", $tags="", $link="")
Container(Salesforce.ProductionApp, "Production App", $techn="", $descr="[Standard]", $tags="", $link="")
Container(Salesforce.CanvasserApp, "Canvasser App", $techn="", $descr="[Standard]", $tags="", $link="")
Container(Salesforce.FieldServiceApp, "Field Service App", $techn="", $descr="[Standard]", $tags="", $link="")

Container_Boundary("Salesforce.ReportsDashboards_boundary", "Reports/Dashboards", $tags="") {
  Component(Salesforce.ReportsDashboards.IndividualCanvasserDashboard, "Individual Canvasser Dashboard", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ReportsDashboards.ManagerCanvasserDashboard, "Manager Canvasser Dashboard", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ReportsDashboards.IndividualSalesDashboard, "Individual Sales Dashboard", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ReportsDashboards.ManagerSalesDashboard, "Manager Sales Dashboard", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ReportsDashboards.IndividualProjectManagerDashboard, "Individual Project Manager Dashboard", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ReportsDashboards.ProjectManagerDashboard, "Project Manager Dashboard", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ReportsDashboards.IndividualDispatcherDashboard, "Individual Dispatcher Dashboard", $techn="", $descr="", $tags="", $link="")
}

Rel(Salesforce.SalesApp, Salesforce.ReportsDashboards.IndividualSalesDashboard, "Has", $techn="", $tags="", $link="")
Rel(Salesforce.CanvasserApp, Salesforce.ReportsDashboards.IndividualCanvasserDashboard, "Has", $techn="", $tags="", $link="")
Rel(Salesforce.ProductionApp, Salesforce.ReportsDashboards.IndividualProjectManagerDashboard, "Has", $techn="", $tags="", $link="")
Rel(Salesforce.FieldServiceApp, Salesforce.ReportsDashboards.ProjectManagerDashboard, "Has", $techn="", $tags="", $link="")
Rel(Salesforce.FieldServiceApp, Salesforce.ReportsDashboards.IndividualDispatcherDashboard, "Has", $techn="", $tags="", $link="")
Rel(Salesforce.SalesApp, Salesforce.ReportsDashboards.ManagerSalesDashboard, "Has", $techn="", $tags="", $link="")
Rel(Salesforce.CanvasserApp, Salesforce.ReportsDashboards.ManagerCanvasserDashboard, "Has", $techn="", $tags="", $link="")
Rel(Salesforce.ProductionApp, Salesforce.ReportsDashboards.ProjectManagerDashboard, "Has", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml