@startuml
set separator none
title Salesforce - Availability Service - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Container(Salesforce.SalesApp, "Sales App", $techn="", $descr="[Standard]", $tags="", $link="")
Container(Salesforce.ProductionApp, "Production App", $techn="", $descr="[Standard]", $tags="", $link="")

Container_Boundary("Salesforce.AvailabilityService_boundary", "Availability Service", $tags="") {
  Component(Salesforce.AvailabilityService.AvailabilityManagerView, "Availability Manager View", $techn="", $descr="Allows users with proper permissions to view and set all availabilities", $tags="", $link="")
  Component(Salesforce.AvailabilityService.AvailabilitySalesView, "Availability Sales View", $techn="", $descr="Allows sales people to view and set their own availabilities", $tags="", $link="")
  Component(Salesforce.AvailabilityService.AvailabilityCrewView, "Availability Crew View", $techn="", $descr="Allows crew leads to view and set their own availabilities", $tags="", $link="")
  Component(Salesforce.AvailabilityService.AvailabilityCalendarBlocking, "Availability Calendar Blocking", $techn="", $descr="Allows certain time periods to be blocked", $tags="", $link="")
  Component(Salesforce.AvailabilityService.AvailabilityShiftCreation, "Availability Shift Creation", $techn="", $descr="Creates shift records behind the scenes", $tags="", $link="")
}

Rel(Salesforce.ProductionApp, Salesforce.AvailabilityService.AvailabilityCrewView, "Sets availability", $techn="", $tags="", $link="")
Rel(Salesforce.SalesApp, Salesforce.AvailabilityService.AvailabilitySalesView, "Sets availability", $techn="", $tags="", $link="")
Rel(Salesforce.AvailabilityService.AvailabilityManagerView, Salesforce.AvailabilityService.AvailabilityShiftCreation, "Creates Shifts", $techn="", $tags="", $link="")
Rel(Salesforce.AvailabilityService.AvailabilitySalesView, Salesforce.AvailabilityService.AvailabilityShiftCreation, "Creates Shifts", $techn="", $tags="", $link="")
Rel(Salesforce.AvailabilityService.AvailabilityCrewView, Salesforce.AvailabilityService.AvailabilityShiftCreation, "Creates Shifts", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml