@startuml
set separator none
title Salesforce - Call Center App - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Person(CallCenter, "Call Center", $descr="", $tags="", $link="")
System(RingCentral, "Ring Central", $descr="Telephony Software", $tags="", $link="")

Container_Boundary("Salesforce.CallCenterApp_boundary", "Call Center App", $tags="") {
  Component(Salesforce.CallCenterApp.AppointmentScheduling, "Appointment Scheduling", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.CallCenterApp.LeadRecordPage, "Lead Record Page", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.CallCenterApp.Omnichannel, "Omnichannel", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.CallCenterApp.RingCentralSalesforcePackage, "Ring Central Salesforce Package", $techn="", $descr="", $tags="", $link="")
}

Rel(CallCenter, RingCentral, "Uses", $techn="", $tags="", $link="")
Rel(Salesforce.CallCenterApp.RingCentralSalesforcePackage, RingCentral, "Calls Leads", $techn="", $tags="", $link="")
Rel(CallCenter, Salesforce.CallCenterApp.LeadRecordPage, "Dials Leads", $techn="", $tags="", $link="")
Rel(CallCenter, Salesforce.CallCenterApp.AppointmentScheduling, "Schedules Sales Appointments", $techn="", $tags="", $link="")
Rel(Salesforce.CallCenterApp.Omnichannel, CallCenter, "Notifies for new Leads", $techn="", $tags="", $link="")
Rel(CallCenter, Salesforce.CallCenterApp.RingCentralSalesforcePackage, "Uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml