@startuml
set separator none
title One Click Contractor - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(Sales, "Sales", $descr="", $tags="", $link="")
System(Salesforce, "Salesforce", $descr="Salesforce CRM", $tags="", $link="")

System_Boundary("OneClickContractor_boundary", "One Click Contractor", $tags="") {
  Container(OneClickContractor.Jobs, "Jobs", $techn="", $descr="", $tags="", $link="")
  Container(OneClickContractor.Estimates, "Estimates", $techn="", $descr="", $tags="", $link="")
}

Rel(Sales, Salesforce, "Uses", $techn="", $tags="", $link="")
Rel(Salesforce, OneClickContractor.Jobs, "Automatically Creates", $techn="", $tags="", $link="")
Rel(OneClickContractor.Estimates, Salesforce, "Estimates are Created", $techn="", $tags="", $link="")
Rel(OneClickContractor.Jobs, Salesforce, "Job is Sold", $techn="", $tags="", $link="")
Rel(Sales, OneClickContractor.Estimates, "Creates Estimates", $techn="", $tags="", $link="")
Rel(Sales, OneClickContractor.Jobs, "Uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml