@startuml
set separator none
title Salesforce - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(Sales, "Sales", $descr="", $tags="", $link="")
Person(Manager, "Manager", $descr="", $tags="", $link="")
Person(CallCenter, "Call Center", $descr="", $tags="", $link="")
Person(Canvasser, "Canvasser", $descr="", $tags="", $link="")
Person(Accounting, "Accounting", $descr="", $tags="", $link="")
Person(ProjectManager, "Project Manager", $descr="", $tags="", $link="")
Person(Dispatcher, "Dispatcher", $descr="", $tags="", $link="")
System(OneClickContractor, "One Click Contractor", $descr="Quoting Software", $tags="", $link="")
System(RingCentral, "Ring Central", $descr="Telephony Software", $tags="", $link="")

System_Boundary("Salesforce_boundary", "Salesforce", $tags="") {
  Container(Salesforce.SalesApp, "Sales App", $techn="", $descr="[Standard]", $tags="", $link="")
  Container(Salesforce.ProductionApp, "Production App", $techn="", $descr="[Standard]", $tags="", $link="")
  Container(Salesforce.CallCenterApp, "Call Center App", $techn="", $descr="[Console]", $tags="", $link="")
  Container(Salesforce.CanvasserApp, "Canvasser App", $techn="", $descr="[Standard]", $tags="", $link="")
  Container(Salesforce.FieldServiceApp, "Field Service App", $techn="", $descr="[Standard]", $tags="", $link="")
  Container(Salesforce.CommissionCalculationService, "Commission Calculation Service", $techn="", $descr="", $tags="", $link="")
  Container(Salesforce.AvailabilityService, "Availability Service", $techn="", $descr="LWC on a custom tab", $tags="", $link="")
  Container(Salesforce.ReportsDashboards, "Reports/Dashboards", $techn="", $descr="", $tags="", $link="")
  Container(Salesforce.PermissionSetGroups, "Permission Set Groups", $techn="", $descr="", $tags="", $link="")
}

Rel(CallCenter, RingCentral, "Uses", $techn="", $tags="", $link="")
Rel(Salesforce.CallCenterApp, RingCentral, "Calls Leads", $techn="", $tags="", $link="")
Rel(Salesforce.ProductionApp, Salesforce.AvailabilityService, "Sets availability", $techn="", $tags="", $link="")
Rel(Salesforce.SalesApp, Salesforce.AvailabilityService, "Sets availability", $techn="", $tags="", $link="")
Rel(Salesforce.SalesApp, Salesforce.CommissionCalculationService, "Calculates Commissions", $techn="", $tags="", $link="")
Rel(Manager, Salesforce.AvailabilityService, "Views and sets all availability", $techn="", $tags="", $link="")
Rel(Salesforce.SalesApp, Salesforce.ReportsDashboards, "Has", $techn="", $tags="", $link="")
Rel(Salesforce.CanvasserApp, Salesforce.ReportsDashboards, "Has", $techn="", $tags="", $link="")
Rel(Salesforce.ProductionApp, Salesforce.ReportsDashboards, "Has", $techn="", $tags="", $link="")
Rel(Salesforce.FieldServiceApp, Salesforce.ReportsDashboards, "Has", $techn="", $tags="", $link="")
Rel(CallCenter, Salesforce.CallCenterApp, "Dials Leads", $techn="", $tags="", $link="")
Rel(Salesforce.CallCenterApp, CallCenter, "Notifies for new Leads", $techn="", $tags="", $link="")
Rel(ProjectManager, Salesforce.FieldServiceApp, "Uses", $techn="", $tags="", $link="")
Rel(ProjectManager, Salesforce.ProductionApp, "Schedules Crews", $techn="", $tags="", $link="")
Rel(Manager, Salesforce.SalesApp, "Views Reports", $techn="", $tags="", $link="")
Rel(Manager, Salesforce.CanvasserApp, "Views Reports", $techn="", $tags="", $link="")
Rel(Manager, Salesforce.ProductionApp, "Views Reports", $techn="", $tags="", $link="")
Rel(Sales, Salesforce.SalesApp, "Uses", $techn="", $tags="", $link="")
Rel(Canvasser, Salesforce.CanvasserApp, "Dials Leads", $techn="", $tags="", $link="")
Rel(Dispatcher, Salesforce.FieldServiceApp, "Dispatches sales people and production teams", $techn="", $tags="", $link="")
Rel(Dispatcher, Salesforce.ProductionApp, "Views all availabilities", $techn="", $tags="", $link="")
Rel(Sales, OneClickContractor, "Uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml