@startuml
set separator none
title Lead Aggregators - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(Salesforce, "Salesforce", $descr="Salesforce CRM", $tags="", $link="")

System_Boundary("LeadAggregators_boundary", "Lead Aggregators", $tags="") {
  Container(LeadAggregators.AngiLeadAggregator, "Angi Lead Aggregator", $techn="", $descr="", $tags="", $link="")
  Container(LeadAggregators.GetTheReferral, "Get The Referral", $techn="", $descr="", $tags="", $link="")
  Container(LeadAggregators.Yelp, "Yelp", $techn="", $descr="", $tags="", $link="")
  Container(LeadAggregators.AngiAds, "Angi Ads", $techn="", $descr="", $tags="", $link="")
  Container(LeadAggregators.Thumbtack, "Thumbtack", $techn="", $descr="", $tags="", $link="")
  Container(LeadAggregators.Google, "Google", $techn="", $descr="", $tags="", $link="")
  Container(LeadAggregators.Meta, "Meta", $techn="", $descr="", $tags="", $link="")
  Container(LeadAggregators.Networx, "Networx", $techn="", $descr="", $tags="", $link="")
}

Rel(LeadAggregators.AngiLeadAggregator, Salesforce, "Creates Leads", $techn="", $tags="", $link="")
Rel(LeadAggregators.GetTheReferral, Salesforce, "Creates Leads", $techn="", $tags="", $link="")
Rel(LeadAggregators.Yelp, Salesforce, "Creates Leads", $techn="", $tags="", $link="")
Rel(LeadAggregators.AngiAds, Salesforce, "Creates Leads", $techn="", $tags="", $link="")
Rel(LeadAggregators.Thumbtack, Salesforce, "Creates Leads", $techn="", $tags="", $link="")
Rel(LeadAggregators.Google, Salesforce, "Creates Leads", $techn="", $tags="", $link="")
Rel(LeadAggregators.Meta, Salesforce, "Creates Leads", $techn="", $tags="", $link="")
Rel(LeadAggregators.Networx, Salesforce, "Creates Leads", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml