@startuml
set separator none
title Opportunity Process

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Container_Boundary("Salesforce.ProcessMaps_boundary", "Process Maps", $tags="") {
  Component(Salesforce.ProcessMaps.Projects, "Projects", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ProcessMaps.ConfirmedOpportunity, "Confirmed Opportunity", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ProcessMaps.IssuedOpportunity, "Issued Opportunity", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ProcessMaps.SoldOpportunity, "Sold Opportunity", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ProcessMaps.ClosedWonOpportunity, "Closed Won Opportunity", $techn="", $descr="", $tags="", $link="")
}

Container(OneClickContractor.Jobs, "Jobs", $techn="", $descr="", $tags="", $link="")
Container(OneClickContractor.Estimates, "Estimates", $techn="", $descr="", $tags="", $link="")

Rel(Salesforce.ProcessMaps.ConfirmedOpportunity, OneClickContractor.Jobs, "1. Automatically Creates", $techn="", $tags="", $link="")
Rel(Salesforce.ProcessMaps.ConfirmedOpportunity, Salesforce.ProcessMaps.IssuedOpportunity, "2. Appointment Issued to Sales Person", $techn="", $tags="", $link="")
Rel(OneClickContractor.Estimates, Salesforce.ProcessMaps.IssuedOpportunity, "3. Estimates are Created", $techn="", $tags="", $link="")
Rel(Salesforce.ProcessMaps.IssuedOpportunity, Salesforce.ProcessMaps.SoldOpportunity, "4. Sold", $techn="", $tags="", $link="")
Rel(OneClickContractor.Jobs, Salesforce.ProcessMaps.SoldOpportunity, "5. Job is Sold", $techn="", $tags="", $link="")
Rel(Salesforce.ProcessMaps.SoldOpportunity, Salesforce.ProcessMaps.Projects, "6. Manually create projects (required step)", $techn="", $tags="", $link="")
Rel(Salesforce.ProcessMaps.Projects, Salesforce.ProcessMaps.ClosedWonOpportunity, "7. Won", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml