@startuml
set separator none
title Lead Process

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("Salesforce.ProcessMaps_boundary", "Process Maps", $tags="") {
  Component(Salesforce.ProcessMaps.NewLead, "New Lead", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ProcessMaps.SetLead, "Set Lead", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ProcessMaps.VerifiedLead, "Verified Lead", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ProcessMaps.ConfirmedLead, "Confirmed Lead", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ProcessMaps.Opportunities, "Opportunities", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ProcessMaps.Accounts, "Accounts", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ProcessMaps.Contacts, "Contacts", $techn="", $descr="", $tags="", $link="")
  Component(Salesforce.ProcessMaps.Projects, "Projects", $techn="", $descr="", $tags="", $link="")
}

Rel(Salesforce.ProcessMaps.NewLead, Salesforce.ProcessMaps.SetLead, "1. Appointment is Set", $techn="", $tags="", $link="")
Rel(Salesforce.ProcessMaps.SetLead, Salesforce.ProcessMaps.VerifiedLead, "2. Appointment is Verified", $techn="", $tags="", $link="")
Rel(Salesforce.ProcessMaps.VerifiedLead, Salesforce.ProcessMaps.ConfirmedLead, "3. Appointment is Confirmed", $techn="", $tags="", $link="")
Rel(Salesforce.ProcessMaps.ConfirmedLead, Salesforce.ProcessMaps.Opportunities, "4. Converts", $techn="", $tags="", $link="")
Rel(Salesforce.ProcessMaps.ConfirmedLead, Salesforce.ProcessMaps.Accounts, "5. Converts", $techn="", $tags="", $link="")
Rel(Salesforce.ProcessMaps.ConfirmedLead, Salesforce.ProcessMaps.Contacts, "6. Converts", $techn="", $tags="", $link="")
Rel(Salesforce.ProcessMaps.Opportunities, Salesforce.ProcessMaps.Projects, "7. Creates", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml