name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Download Structurizr Site Generatr
        run: |
          VERSION=1.5.2
          wget https://github.com/avisi-cloud/structurizr-site-generatr/releases/download/${VERSION}/structurizr-site-generatr-${VERSION}.zip
          unzip structurizr-site-generatr-${VERSION}.zip
          chmod +x structurizr-site-generatr-${VERSION}/bin/structurizr-site-generatr

      - name: Generate site
        run: ./structurizr-site-generatr-1.5.2/bin/structurizr-site-generatr generate-site --workspace-file diagram.dsl

      - name: Add .nojekyll file
        run: touch build/site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site
          publish_branch: gh-pages
